### PR TITLE
Removed reference to `water.mss` which seems to be missing.

### PR DESCRIPTION
**Pull request by zerebubuth**

### CODE REVIEW

**Comment by zerebubuth** [comment]
cc @pnorman

**Comment by pnorman** [comment]
https://github.com/MapQuest/mq-carto-style-vector/blob/master/mq-carto-style.tm2/water.mss

**Comment by zerebubuth** [comment]
Sure, but no https://github.com/MapQuest/mq-carto-style-vector/tree/cts/mq-carto-style.tm2/water.mss - is the CTS branch still where CTS work is taking place, or is master CTS now?

**Comment by pnorman** [comment]
cleared up the misleading cts branch

**Pull request closed without merging**
